// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_log_bf_var_cpp
NumericVector calc_log_bf_var_cpp(IntegerVector var_case, IntegerVector var_contr, NumericVector gamma_vec, NumericVector sigma_vec, double N1, double N0);
RcppExport SEXP _mirageV2_calc_log_bf_var_cpp(SEXP var_caseSEXP, SEXP var_contrSEXP, SEXP gamma_vecSEXP, SEXP sigma_vecSEXP, SEXP N1SEXP, SEXP N0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type var_case(var_caseSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type var_contr(var_contrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma_vec(gamma_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sigma_vec(sigma_vecSEXP);
    Rcpp::traits::input_parameter< double >::type N1(N1SEXP);
    Rcpp::traits::input_parameter< double >::type N0(N0SEXP);
    rcpp_result_gen = Rcpp::wrap(calc_log_bf_var_cpp(var_case, var_contr, gamma_vec, sigma_vec, N1, N0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mirageV2_calc_log_bf_var_cpp", (DL_FUNC) &_mirageV2_calc_log_bf_var_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_mirageV2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
