# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_log_bf_var_cpp <- function(var_case, var_contr, gamma_vec, sigma_vec, N1, N0) {
    .Call('_mirageV2_calc_log_bf_var_cpp', PACKAGE = 'mirageV2', var_case, var_contr, gamma_vec, sigma_vec, N1, N0)
}

